apiVersion: nsclass.nsclass.laverya.com/v1alpha1
kind: NamespaceClass
metadata:
  labels:
    app.kubernetes.io/name: nsclass-controller
    app.kubernetes.io/managed-by: kustomize
  name: namespaceclass-sample
spec:
  removalPolicy: Delete
  resources:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: namespace-defaults
    data:
      profile: sample
      owner: platform
  - apiVersion: v1
    kind: ResourceQuota
    metadata:
      name: namespace-quota
    spec:
      hard:
        configmaps: "20"
        secrets: "20"
        pods: "20"
